"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nvl&+-3ugb0cjy3^mtio6ist2@wt6hc%m1ii6cw87u=5w*vg6i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['0.0.0.0', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #rest app
    'rest_framework',
    #user app
    'consultaweb.apps.users',
    #jwt token app
    'rest_framework_simplejwt',
    #cors
    'corsheaders',
    
]
#Cors configuration
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Frontend domain
]

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
    "x-csrftoken",
    "x-requested-with",
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'consultaweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'consultaweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
   
   }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#model used for authentication
AUTH_USER_MODEL = 'users.CustomUser'
# simple jwt configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),  # Life of the token
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),    # Life of the refresh token
    'ROTATE_REFRESH_TOKENS': True,  # Automatically renew refresh token
    'BLACKLIST_AFTER_ROTATION': True,  # Invalidate old token
}

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {message}", # Logging type
            "style": "{",
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        "info_file": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": os.path.join(BASE_DIR, 'consultaweb/logs/info_logs/consultaweb_info_logs.log'), # Info log Pathing
            "when": "midnight",  # Daily rotation
            "interval": 1,       # New log each 7 days
            "backupCount": 0,    # Keep the files, dont delete them
            "formatter": "verbose",
            "encoding": "utf-8",
        },
        "warning_file": {
            "level": "WARNING",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": os.path.join(BASE_DIR, 'consultaweb/logs/warning_logs/consultaweb_warning_logs.log'), # Warning log Pathing
            "when": "midnight",  # Daily rotation
            "interval": 1,       # New log each 7 days
            "backupCount": 0,    # Keep the files, dont delete them
            "formatter": "verbose",
            "encoding": "utf-8",
        },
        "error_file": {
            "level": "ERROR",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": os.path.join(BASE_DIR, 'consultaweb/logs/error_logs/consultaweb_error_logs.log'), # Error log Pathing
            "when": "midnight",  # Daily rotation
            "interval": 1,       # New log each 7 days
            "backupCount": 0,    # Keep the files, dont delete them
            "formatter": "verbose",
            "encoding": "utf-8",
        },
        "general_file": {
            "level": "DEBUG",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": os.path.join(BASE_DIR, 'consultaweb/logs/general_logs/consultaweb_general_logs.log'), # General (All) logs pathing
            "when": "midnight",   # Daily rotation
            "interval": 1,        # New log each 7 days
            "backupCount": 0,     # Keep the files, dont delete them
            "formatter": "verbose",
            "encoding": "utf-8",
        },
    },
    'loggers': {
        'info_logger': {
            'handlers': ['info_file', 'general_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'warning_logger': {
            'handlers': ['warning_file', 'general_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'error_logger': {
            'handlers': ['error_file', 'general_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'general_logger': {
            'handlers': ['general_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}